# Generated by Django 2.0.7 on 2018-07-08 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reserv',
            new_name='Reserve',
        ),
        migrations.AlterModelOptions(
            name='reserve',
            options={'verbose_name': 'Reserve', 'verbose_name_plural': 'Reserves'},
        ),
    ]
